const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage...",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "Trending",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city...",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "Rooms",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind...",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "Mountain",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany...",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "Iconic city",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops...",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    price: 800,
    location: "Portland",
    country: "United States",
    category: "Camping",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out onto the sandy beach...",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: "Amazing Pools",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing...",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: "Farms",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living...",
    image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: "Iconic city",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep...",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    category: "Mountain",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the wild...",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e",
    price: 4000,
    location: "Serengeti",
    country: "Tanzania",
    category: "Trending",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island...",
    image: "https://images.unsplash.com/photo-1618140052121-39fc6db33972",
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    category: "Domes",
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty...",
    image: "https://images.unsplash.com/photo-1585543805890-6051f7829f98",
    price: 4000,
    location: "Scotland",
    country: "United Kingdom",
    category: "Castles",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the desert...",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090",
    price: 5000,
    location: "Dubai",
    country: "UAE",
    category: "Trending",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise...",
    image: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9",
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    category: "Amazing Pools",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views...",
    image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb",
    price: 1500,
    location: "Banff",
    country: "Canada",
    category: "Mountain",
  }
];

module.exports = { data: sampleListings };